name: "ForUm_Prod"

services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    networks:
      - app-tier-prod
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: "12345"
      POSTGRES_DB: mydata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydata"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: server/Dockerfile.prod
    ports:
      - "8000:8000"
    networks:
      - app-tier-prod
    env_file:
      - .env
    environment:
      STATIC_DIR: "/app/client/dist"
    depends_on:
      db:
        condition: service_healthy

networks:
  app-tier-prod:
    driver: bridge
